# Generated by Django 3.2.8 on 2022-01-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/Donor/'),
        ),
    ]
